global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'Udapeople'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA4H7SEQ7M5UAD4WIN
        secret_key: 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
        port: 9100